"use client";

import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { api } from "@/lib/api";
import { getErrorMessage } from "@/lib/utils";
import { Sparkles, Bot } from "lucide-react";

interface CreateIssueDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  workspaceId: number;
  onIssueCreated: (issue: any) => void;
  members?: any[];
}

export function CreateIssueDialog({
  open,
  onOpenChange,
  workspaceId,
  onIssueCreated,
  members,
}: CreateIssueDialogProps) {
  console.log(members)
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [issueType, setIssueType] = useState("task");
  const [status, setStatus] = useState("todo");
  const [priority, setPriority] = useState("medium");
  const [assigneeId, setAssigneeId] = useState<string>("unassigned");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [isAIGenerating, setIsAIGenerating] = useState(false);

  const handleAIGenerate = async () => {
    if (!title.trim() || isAIGenerating) return;
    
    setIsAIGenerating(true);
    setError("");
    
    try {
      // 1. Determine Type and Priority instantly based on keywords
      const lowerTitle = title.toLowerCase();
      
      let newType = "story";
      if (lowerTitle.includes("fix") || lowerTitle.includes("bug") || lowerTitle.includes("broken") || lowerTitle.includes("error")) newType = "bug";
      if (lowerTitle.includes("epic") || lowerTitle.includes("initiative")) newType = "epic";
      if (lowerTitle.includes("update") || lowerTitle.includes("add")) newType = "task";
      
      let newPriority = "medium";
      if (lowerTitle.includes("urgent") || lowerTitle.includes("critical") || lowerTitle.includes("crash")) newPriority = "highest";
      else if (newType === "bug") newPriority = "high";
      else if (lowerTitle.includes("minor") || lowerTitle.includes("typo")) newPriority = "low";

      setIssueType(newType);
      setPriority(newPriority);
      setDescription("");

      // 2. Simulate streaming markdown generation
      const mockMarkdown = `### AI Analysis
Based on the title "${title}", I've classified this as a **${newType.toUpperCase()}** with **${newPriority.toUpperCase()}** priority.

**Proposed Requirements:**
- Investigate the root cause of the issue described.
- Ensure all related test cases are updated.
- Verify the fix across supported browsers/devices.

**Acceptance Criteria:**
- [ ] Issue is fully resolved.
- [ ] No regressions introduced.

*Generated by AI Auto-Triage.*`;

      const words = mockMarkdown.split(" ");
      let currentDesc = "";
      
      for (let i = 0; i < words.length; i++) {
        currentDesc += words[i] + " ";
        setDescription(currentDesc);
        // Random typing speed between 20ms and 80ms per word
        await new Promise(r => setTimeout(r, Math.random() * 60 + 20));
      }

    } catch (err) {
      console.error(err);
    } finally {
      setIsAIGenerating(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (!title.trim()) {
      setError("Issue title is required");
      return;
    }

    try {
      setLoading(true);
      const res = await api.post(`/workspaces/${workspaceId}/issues`, {
        title: title.trim(),
        description: description.trim() || null,
        issue_type: issueType,
        status: status,
        priority: priority,
        assignee_id: assigneeId === "unassigned" ? null : parseInt(assigneeId),
      });

      onIssueCreated(res.data);

      // Reset form
      setTitle("");
      setDescription("");
      setIssueType("task");
      setStatus("todo");
      setPriority("medium");
      setAssigneeId("unassigned");
      onOpenChange(false);
    } catch (err: any) {
      setError(getErrorMessage(err, "Failed to create issue"));
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <form onSubmit={handleSubmit} className="space-y-4">
          <DialogHeader>
            <DialogTitle>Create New Issue</DialogTitle>
            <DialogDescription>
              Add a new task, bug, story, or epic to your board.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3.5 py-1">
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <Label htmlFor="issue-title">Title</Label>
                <Button 
                  type="button" 
                  variant="ghost" 
                  size="sm" 
                  className="h-6 px-2 text-xs gap-1.5 text-indigo-500 hover:text-indigo-400 hover:bg-indigo-500/10 font-medium"
                  onClick={handleAIGenerate}
                  disabled={!title.trim() || isAIGenerating}
                >
                  {isAIGenerating ? (
                    <Bot size={14} className="animate-pulse" />
                  ) : (
                    <Sparkles size={14} />
                  )}
                  {isAIGenerating ? "Thinking..." : "Auto-fill with AI"}
                </Button>
              </div>
              <Input
                id="issue-title"
                placeholder="What needs to be done?"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                disabled={isAIGenerating || loading}
                required
              />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="issue-description">Description (Optional)</Label>
              <textarea
                id="issue-description"
                rows={10}
                placeholder="Add more details, requirements, or reproduction steps..."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                disabled={isAIGenerating || loading}
                className={`w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-xs placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring transition-colors ${
                  isAIGenerating ? "border-indigo-500/50 bg-indigo-500/5 ring-1 ring-indigo-500/20" : ""
                }`}
              />
            </div>

            <div className="grid grid-cols-3 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="issue-type">Type</Label>
                <select
                  id="issue-type"
                  value={issueType}
                  onChange={(e) => setIssueType(e.target.value)}
                  className="w-full h-9 rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring cursor-pointer"
                >
                  <option value="task">Task</option>
                  <option value="bug">Bug</option>
                  <option value="story">Story</option>
                  <option value="epic">Epic</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <Label htmlFor="issue-status">Status</Label>
                <select
                  id="issue-status"
                  value={status}
                  onChange={(e) => setStatus(e.target.value)}
                  className="w-full h-9 rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring cursor-pointer"
                >
                  <option value="todo">To Do</option>
                  <option value="in_progress">In Progress</option>
                  <option value="done">Done</option>
                  <option value="backlog">Backlog</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <Label htmlFor="issue-priority">Priority</Label>
                <select
                  id="issue-priority"
                  value={priority}
                  onChange={(e) => setPriority(e.target.value)}
                  className="w-full h-9 rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring cursor-pointer"
                >
                  <option value="lowest">Lowest</option>
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                  <option value="highest">Highest</option>
                </select>
              </div>
            </div>

            <div className="space-y-1.5 pt-1">
              <Label htmlFor="issue-assignee">Assignee</Label>
              <select
                id="issue-assignee"
                value={assigneeId}
                onChange={(e) => setAssigneeId(e.target.value)}
                disabled={isAIGenerating || loading}
                className="w-full h-9 rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring cursor-pointer"
              >
                <option value="unassigned">Unassigned</option>
                {members?.map((m: any) => (
                  <option key={m.id} value={m.user_id}>
                    {m.user?.full_name || m.user?.username || m.user?.email}
                  </option>
                ))}
              </select>
            </div>

            {error && <p className="text-xs font-medium text-destructive">{error}</p>}
          </div>

          <DialogFooter className="gap-2 sm:gap-0">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={loading || isAIGenerating}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={loading || isAIGenerating}>
              {loading ? "Creating..." : "Create Issue"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
